### ISSUE TITLE
`commitlint` workflow not using `edx-lint` config

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/.github#163]
The `commitlint` workflow is using
https://github.com/openedx/.github/blob/5d7768975300f76590cd57054f42574c69a780fa/.github/workflows/commitlint.yml#L32

The [README for that action](https://github.com/wagoid/commitlint-github-action?tab=readme-ov-file#configfile) says
> Default: `commitlint.config.mjs`
> 
> If the config file doesn't exist, [config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) settings will be loaded as a default fallback.
> [ ... ]
> Note: `commitlint.config.js` doesn't work with this action. If you use a JS config file, it's required to be an ES Module (`.mjs` extension)

Logs from workflow runs match the documentation

```
Run wagoid/commitlint-github-action@v6
  with:
    configFile: ./commitlint.config.mjs
    failOnWarnings: false
    failOnErrors: true
    helpURL: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
    token: ***
```

So the workflow file is downloading https://github.com/openedx/edx-lint/blob/master/edx_lint/files/commitlint.config.js, naming it `commitlint.config.cjs`, and then not using it at all (and instead just falling back to an unmodified version of [config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional)
